base_lr: 0.1
config:
- !!python/object:jsonargparse.util.Path
  abs_path: C:\Users\3neut\DFCIL\rdfcil\cifar100.yaml
  cwd: C:\Users\3neut\DFCIL\rdfcil
  is_fsspec: false
  is_url: false
  mode: fsr
  rel_path: cifar100.yaml
  skip_check: false
data:
  batch_size: 128
  class_order: []
  current_task: 0
  dataset: cifar100
  dynamic_memory: false
  init_task_splits: 0
  memory_algo: herding
  memory_size: 0
  num_tasks: 5
  num_workers: 4
  root: ~/data/dataset
  task_seed: 42
  test_mode: seen
  val_seed: 42
  val_splits: 0
finetuning_epochs: 40
finetuning_lr: 0.005
inv_alpha_pr: 0.001
inv_alpha_rf: 50.0
inv_lr: 0.001
inv_resume_from: null
inv_tau: 1000.0
lambda_ce: 0.5
lambda_hkd: 0.15
lambda_rkd: 0.5
lr_factor: 0.1
milestones:
- 80
- 120
model:
  base_lr: 0.1
  finetuning_epochs: 40
  finetuning_lr: 0.005
  inv_alpha_pr: 0.001
  inv_alpha_rf: 50.0
  inv_lr: 0.001
  inv_resume_from: null
  inv_tau: 1000.0
  lambda_ce: 0.5
  lambda_hkd: 0.15
  lambda_rkd: 0.5
  lr_factor: 0.1
  milestones:
  - 80
  - 120
  momentum: 0.9
  num_inv_iters: 5000
  weight_decay: 0.0005
momentum: 0.9
num_inv_iters: 5000
seed_everything: 1662273161
trainer:
  accelerator: null
  accumulate_grad_batches: 1
  amp_backend: native
  amp_level: O2
  auto_lr_find: false
  auto_scale_batch_size: false
  auto_select_gpus: false
  benchmark: true
  callbacks: null
  check_val_every_n_epoch: 40
  checkpoint_callback: false
  default_root_dir: null
  deterministic: true
  devices: null
  distributed_backend: null
  fast_dev_run: false
  flush_logs_every_n_steps: 100
  gpus: -1
  gradient_clip_algorithm: norm
  gradient_clip_val: 0.0
  ipus: null
  limit_predict_batches: 1.0
  limit_test_batches: 1.0
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  log_every_n_steps: 50
  log_gpu_memory: null
  logger: true
  max_epochs: 200
  max_steps: null
  max_time: null
  min_epochs: null
  min_steps: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  num_nodes: 1
  num_processes: 1
  num_sanity_val_steps: 0
  overfit_batches: 0.0
  plugins: null
  precision: 32
  prepare_data_per_node: true
  process_position: 0
  profiler: null
  progress_bar_refresh_rate: null
  reload_dataloaders_every_epoch: false
  reload_dataloaders_every_n_epochs: 0
  replace_sampler_ddp: false
  resume_from_checkpoint: null
  stochastic_weight_avg: false
  sync_batchnorm: false
  terminate_on_nan: false
  tpu_cores: null
  track_grad_norm: -1
  truncated_bptt_steps: null
  val_check_interval: 1.0
  weights_save_path: null
  weights_summary: top
weight_decay: 0.0005
